# importing librraies

In [1]:
import numpy as np
import pandas as pd

# Loading Datasets

In [2]:
df=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/balance-scale/balance-scale.data')
print(df.head())

   B  1  1.1  1.2  1.3
0  R  1    1    1    2
1  R  1    1    1    3
2  R  1    1    1    4
3  R  1    1    1    5
4  R  1    1    2    1


In [3]:


df.shape



(624, 5)

# Slice the dataset. Save the first column as y(Target) and rest of the columns as X(Features).

In [4]:
y_target=df.iloc[:,0]
print(y_target.head())

0    R
1    R
2    R
3    R
4    R
Name: B, dtype: object


In [5]:
x_feature=df.iloc[:,1:]
x_feature.head()

1  1.1  1.2  1.3
0  1    1    1    2
1  1    1    1    3
2  1    1    1    4
3  1    1    1    5
4  1    1    2    1

# Split the dataset by using train_test_split()

In [6]:
from sklearn.model_selection import train_test_split as tts
X_train, X_test, y_train, y_test = tts(x_feature, y_target, test_size = 0.3, random_state=42)

# Use DecisionTree with criterion

In [7]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [8]:
pred_y = model.predict(X_test)

In [9]:
result = pd.DataFrame({'Actual': y_test, 'Predicted':pred_y})
print(result)

    Actual Predicted
446      R         B
496      L         L
215      B         L
212      R         R
479      L         L
501      L         L
163      R         R
77       B         L
526      L         L
145      R         R
265      R         R
31       R         R
55       R         B
90       R         R
556      L         L
76       L         L
2        R         R
367      R         R
395      R         R
334      L         L
131      R         R
148      R         R
49       L         L
620      L         L
316      R         B
110      R         R
257      R         R
577      L         L
619      L         L
256      R         R
..     ...       ...
165      R         R
465      L         L
335      L         L
213      R         R
137      R         R
399      L         L
605      L         L
176      L         L
9        R         R
495      L         L
238      R         R
322      R         R
609      L         L
268      R         R
84       L         B
290      R   

# Print the accuracy score.

In [10]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,pred_y)
#print("The accuracy score is : {}".format(accuracy_score))

0.8085106382978723

In [11]:
from sklearn.metrics import confusion_matrix as cm, classification_report as cr
print(cm(y_test, pred_y))
print(cr(y_test, pred_y))

[[ 1  8  3]
 [11 76  0]
 [12  2 75]]
             precision    recall  f1-score   support

          B       0.04      0.08      0.06        12
          L       0.88      0.87      0.88        87
          R       0.96      0.84      0.90        89

avg / total       0.87      0.81      0.84       188



# Use RandomForset with criterion

In [12]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_jobs = 2)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=2,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [13]:
pred_y = clf.predict(X_test)

In [14]:
result = pd.DataFrame({'Actual': y_test, 'Predicted':pred_y})
print(result)

    Actual Predicted
446      R         B
496      L         L
215      B         L
212      R         R
479      L         L
501      L         L
163      R         R
77       B         R
526      L         L
145      R         R
265      R         R
31       R         R
55       R         L
90       R         R
556      L         L
76       L         L
2        R         R
367      R         R
395      R         R
334      L         L
131      R         R
148      R         R
49       L         L
620      L         L
316      R         R
110      R         R
257      R         R
577      L         L
619      L         L
256      R         R
..     ...       ...
165      R         R
465      L         L
335      L         L
213      R         R
137      R         R
399      L         L
605      L         L
176      L         L
9        R         R
495      L         L
238      R         R
322      R         R
609      L         L
268      R         R
84       L         B
290      R   

In [15]:
from sklearn.metrics import confusion_matrix as cm, classification_report as cr
print(cm(y_test, pred_y))
print(cr(y_test, pred_y))

[[ 0  7  5]
 [ 9 78  0]
 [ 6  4 79]]
             precision    recall  f1-score   support

          B       0.00      0.00      0.00        12
          L       0.88      0.90      0.89        87
          R       0.94      0.89      0.91        89

avg / total       0.85      0.84      0.84       188



# Print the accuracy score

In [16]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,pred_y)

0.8351063829787234